repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]

  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: bash -c 'flake8 --max-line-length=120 --extend-ignore=E203,W503 src/ tests/'
        language: system
        files: \.py$

      - id: mypy
        name: mypy
        entry: bash -c 'mypy --explicit-package-bases src/'
        language: system
        files: \.py$

      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [tests/]